### ISSUE TITLE
注册配置项修改事件永远未触发

### ISSUE THREAD

**Issue by QQ897878763** [kklldog/AgileConfig#28]
引入AgileConfig代码是这样的
```
 host.ConfigureAppConfiguration((context, config) =>
            {
              
                //new一个client实例，无参构造会从本地appsettings.json文件读取配置
                var configClient = new ConfigClient($"appsettings.{context.HostingEnvironment.EnvironmentName}.json");
                //使用AddAgileConfig配置一个新的IConfigurationSource
                config.AddAgileConfig(configClient);
                //注册配置项修改事件
                configClient.ConfigChanged += ConfigClient_ConfigChanged; 
            });


        private static void ConfigClient_ConfigChanged(ConfigChangedArg obj)
        {
            Console.WriteLine($"配置项更改!更改信息={obj.Serialize2Json()}");
        }
```
经观察修改正在运行的配置项后，ConfigClient_ConfigChanged没有被触发

**Comment by QQ897878763** [comment]
查看docker发现有错误日志
```
AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware[0]
      Handle websocket client 42baaed6-5364-4fdb-b16c-b3c29e4883eb err .
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.Handle(HttpContext context, WebsocketClient socketClient, IConfigService configService) in /src/AgileConfig.Server.Apisite/Websocket/WebsocketHandlerMiddleware.cs:line 137
   at AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.Invoke(HttpContext context, IAppBasicAuthService appBasicAuth, IConfigService configService) in /src/AgileConfig.Server.Apisite/Websocket/WebsocketHandlerMiddleware.cs:line 110
fail: AgileConfig.Server.Common.ExceptionHandlerMiddleware[0]
      When ::ffff:113.218.174.175 request /ws error , but not handled .
       StatusCode cannot be set because the response has already started. 
          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
         at AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.Invoke(HttpContext context, IAppBasicAuthService appBasicAuth, IConfigService configService) in /src/AgileConfig.Server.Apisite/Websocket/WebsocketHandlerMiddleware.cs:line 110
         at AgileConfig.Server.Apisite.UIExtension.ReactUIMiddleware.Invoke(HttpContext context) in /src/AgileConfig.Server.Apisite/UIExtension/ReactUIMiddleware.cs:line 127
         at AgileConfig.Server.Common.ExceptionHandlerMiddleware.Invoke(HttpContext context) in /src/AgileConfig.Server.Common/ExceptionHandlerMiddleware.cs:line 56

```
但是我的项目启动后可以获取到配置信息，不过在agileConfig后台没看到客户端连接信息

**Comment by QQ897878763** [comment]
查看docker发现有错误日志
```
AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware[0]
      Handle websocket client 42baaed6-5364-4fdb-b16c-b3c29e4883eb err .
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.Handle(HttpContext context, WebsocketClient socketClient, IConfigService configService) in /src/AgileConfig.Server.Apisite/Websocket/WebsocketHandlerMiddleware.cs:line 137
   at AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.Invoke(HttpContext context, IAppBasicAuthService appBasicAuth, IConfigService configService) in /src/AgileConfig.Server.Apisite/Websocket/WebsocketHandlerMiddleware.cs:line 110
fail: AgileConfig.Server.Common.ExceptionHandlerMiddleware[0]
      When ::ffff:113.218.174.175 request /ws error , but not handled .
       StatusCode cannot be set because the response has already started. 
          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
         at AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.Invoke(HttpContext context, IAppBasicAuthService appBasicAuth, IConfigService configService) in /src/AgileConfig.Server.Apisite/Websocket/WebsocketHandlerMiddleware.cs:line 110
         at AgileConfig.Server.Apisite.UIExtension.ReactUIMiddleware.Invoke(HttpContext context) in /src/AgileConfig.Server.Apisite/UIExtension/ReactUIMiddleware.cs:line 127
         at AgileConfig.Server.Common.ExceptionHandlerMiddleware.Invoke(HttpContext context) in /src/AgileConfig.Server.Common/ExceptionHandlerMiddleware.cs:line 56

```
但是我的项目启动后可以获取到配置信息，不过在agileConfig后台没看到客户端连接信息

**Comment by kklldog** [comment]
看来是websocket连接建不起来，内网是不是有nginx代理？如果nginx代理，默认是不支持websocket协议的，需要单独配置

**Comment by QQ897878763** [comment]
服务器目前是部署在阿里云，未配置nginx

**Comment by kklldog** [comment]
这就奇怪了。你试试用你的client连我这个server http://agileconfig.xbaby.xyz:5000 
appId test_app 密码没有
你看看能不能连上去

**Comment by QQ897878763** [comment]
哈哈，今天晚上试下，昨天后面睡了。不过有个建议，热加载可以使用多种方式混合用，至少有个兜底方案。比websocket失败后走轮询或者长链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月10日(周一) 凌晨1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kklldog/AgileConfig] 注册配置项修改事件永远未触发 (#28)




 
这就奇怪了。你试试用你的client连我这个server http://agileconfig.xbaby.xyz:5000
 appId test_app 密码没有
 你看看能不能连上去

**Comment by kklldog** [comment]
> 哈哈，今天晚上试下，昨天后面睡了。不过有个建议，热加载可以使用多种方式混合用，至少有个兜底方案。比websocket失败后走轮询或者长链接
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月10日(周一) 凌晨1:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [kklldog/AgileConfig] 注册配置项修改事件永远未触发 (#28) 这就奇怪了。你试试用你的client连我这个server http://agileconfig.xbaby.xyz:5000 appId test_app 密码没有 你看看能不能连上去 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，正在考虑，看起来http长轮询的兼容性要比websocket高。

**Comment by QQ897878763** [comment]
是的 apollo的长连接是真的稳定，我们可以做兜底方案的 websocket在连续终端N次后 转长连接



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kklldog/AgileConfig] 注册配置项修改事件永远未触发 (#28)





  
哈哈，今天晚上试下，昨天后面睡了。不过有个建议，热加载可以使用多种方式混合用，至少有个兜底方案。比websocket失败后走轮询或者长链接
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年5月10日(周一) 凌晨1:18 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [kklldog/AgileConfig] 注册配置项修改事件永远未触发 (#28) 这就奇怪了。你试试用你的client连我这个server http://agileconfig.xbaby.xyz:5000 appId test_app 密码没有 你看看能不能连上去 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
好的，正在考虑，看起来http长轮询的兼容性要比websocket高。

**Comment by kklldog** [comment]
修复了修改父应用配置项不通知子应用热更新的问题。
