### ISSUE TITLE
使用PostgreSql数据库报错

### ISSUE THREAD

**Issue by wlclass** [kklldog/AgileConfig#38]
尝试将AgileConfig部署在docker desktop中连接宿主机上的PostgreSql数据库，在进行一些编辑操作时，会产生异常，容器停止工作。

  部署命令：
> docker run  --restart=always  -e adminConsole=true  -e db:provider=npgsql -e db:conn="Host=gateway.docker.internal;Port=5432;Username=user;Password=123456;Database=config"  -p 5009:5000  -v /etc/localtime:/etc/localtime   --name agile_config  kklldog/agile_config:latest

大概有两种类型的报错：
- System.InvalidOperationException: A transaction is already in progress; nested/concurrent transactions aren't supported.
- Npgsql.NpgsqlOperationInProgressException: The connection is already in state 'Executing'

以下是其中一种的log输出：

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {d63c1e47-8e71-4f4e-8faa-b99b82db5293} may be persisted to storage in unencrypted form.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:80'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
info: AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware[0]
      Websocket client 7b7faabb-a438-40d2-be50-991561870bac Added
info: AgileConfig.Server.Apisite.Controllers.RemoteServerProxyController[0]
      Request remote node http://gateway.docker.internal:5009 's action OneClientDoAction success .
info: AgileConfig.Server.Apisite.Controllers.RemoteServerProxyController[0]
      Request remote node http://gateway.docker.internal:5009 's action AllClientsDoAction success .
info: AgileConfig.Server.Apisite.Controllers.RemoteServerProxyController[0]
      Request remote node http://gateway.docker.internal:5009 's action OneClientDoAction success .
fail: AgileConfig.Server.Common.TinyEventBus[0]
      fire event OFFLINE_CONFIG_SUCCESS error
Npgsql.NpgsqlOperationInProgressException: The connection is already in state 'Executing'
   at FreeSql.UnitOfWork.Rollback()
   at FreeSql.UnitOfWork.Dispose()
   at FreeSql.DbContext.Dispose()
   at AgileConfig.Server.Service.SysLogService.Dispose() in /src/AgileConfig.Server.Service/SysLogService.cs:line 64
   at AgileConfig.Server.Service.EventRegister.<RegisterAddSysLog>b__9_11(Object param) in /src/AgileConfig.Server.Service/EventRegister.cs:line 470
   at AgileConfig.Server.Common.TinyEventBus.<>c__DisplayClass6_1.<Fire>b__0() in /src/AgileConfig.Server.Common/TinyEventBus.cs:line 101
fail: AgileConfig.Server.Common.TinyEventBus[0]
      fire event PUBLISH_CONFIG_SUCCESS error
Npgsql.NpgsqlOperationInProgressException: A command is already in progress: INSERT INTO "agc_sys_log"("app_id", "log_type", "log_time", "log_text") VALUES(@AppId_0, @LogType_0, @LogTime_0, @LogText_0) RETURNING "id"
   at FreeSql.UnitOfWork.Rollback()
   at FreeSql.UnitOfWork.Dispose()
   at FreeSql.DbContext.Dispose()
   at AgileConfig.Server.Service.SysLogService.Dispose() in /src/AgileConfig.Server.Service/SysLogService.cs:line 64
   at AgileConfig.Server.Service.EventRegister.<RegisterAddSysLog>b__9_12(Object param) in /src/AgileConfig.Server.Service/EventRegister.cs:line 494
   at AgileConfig.Server.Common.TinyEventBus.<>c__DisplayClass6_1.<Fire>b__0() in /src/AgileConfig.Server.Common/TinyEventBus.cs:line 101
Unhandled exception. System.InvalidOperationException: A transaction is already in progress; nested/concurrent transactions aren't supported.
   at FreeSql.UnitOfWork.GetOrBeginTransaction(Boolean isCreate)
   at FreeSql.DbSet`1.OrmInsert()
   at FreeSql.DbSet`1.OrmInsert(TEntity data)
   at FreeSql.DbSet`1.AddPrivAsync(TEntity data, Boolean isCheck)
   at AgileConfig.Server.Service.SysLogService.AddSysLogAsync(SysLog log) in /src/AgileConfig.Server.Service/SysLogService.cs:line 32
   at AgileConfig.Server.Service.RemoteServerNodeProxy.AppClientsDoActionAsync(String address, String appId, WebsocketAction action) in /src/AgileConfig.Server.Service/RemoteServerNodeProxy.cs:line 113
   at AgileConfig.Server.Service.EventRegister.<RegisterWebsocketAction>b__8_3(Object param) in /src/AgileConfig.Server.Service/EventRegister.cs:line 176
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by wlclass** [comment]
![powershell_VksjeKUntz](https://user-images.githubusercontent.com/3060616/125983383-a54d6fdf-aa2f-4481-a97d-7e4f535e2269.png)
![powershell_slOVYDqB9U](https://user-images.githubusercontent.com/3060616/125983393-25b6a259-0d67-4c1a-9f32-577c4b4fde80.png)
![powershell_PQxo3ZEk3R](https://user-images.githubusercontent.com/3060616/125983399-9a5b0894-5378-4a58-a221-1208cfe8b2c4.png)

**Comment by kklldog** [comment]
看起来像是以前修复的一个bug，你的镜像是不是最新的，检测一下sha ？
https://hub.docker.com/layers/kklldog/agile_config/latest/images/sha256-cb7a34fbcf134866684c21966b555d2bdc8818829653b60e8a44250064c0161f?context=repo 这是最新镜像的签名

**Comment by wlclass** [comment]
不好意思，回复晚了，我直接拉的lastest,但sha跟你的不一样，下面是log：

`C:\Users\wlcla>docker pull kklldog/agile_config
Using default tag: latest
latest: Pulling from kklldog/agile_config
69692152171a: Already exists
6142a500eec7: Already exists
98e06df84f9c: Pull complete
ebbd8772c8dd: Pull complete
9c620bc3b6b2: Pull complete
cd2c09735139: Pull complete
f670fdeaedf2: Pull complete
Digest: sha256:c13a870d46f988674291a5e53c6c43efdc0edec727a0df42ecf8cdab22de8be0
Status: Downloaded newer image for kklldog/agile_config:latest
docker.io/kklldog/agile_config:latest

C:\Users\wlcla>docker pull kklldog/agile_config
Using default tag: latest
latest: Pulling from kklldog/agile_config
Digest: sha256:c13a870d46f988674291a5e53c6c43efdc0edec727a0df42ecf8cdab22de8be0
Status: Image is up to date for kklldog/agile_config:latest
docker.io/kklldog/agile_config:latest
`

**Comment by kklldog** [comment]
> 不好意思，回复晚了，我直接拉的lastest,但sha跟你的不一样，下面是log：
> 
> `C:\Users\wlcla>docker pull kklldog/agile_config
> Using default tag: latest
> latest: Pulling from kklldog/agile_config
> 69692152171a: Already exists
> 6142a500eec7: Already exists
> 98e06df84f9c: Pull complete
> ebbd8772c8dd: Pull complete
> 9c620bc3b6b2: Pull complete
> cd2c09735139: Pull complete
> f670fdeaedf2: Pull complete
> Digest: sha256:c13a870d46f988674291a5e53c6c43efdc0edec727a0df42ecf8cdab22de8be0
> Status: Downloaded newer image for kklldog/agile_config:latest
> docker.io/kklldog/agile_config:latest
> 
> C:\Users\wlcla>docker pull kklldog/agile_config
> Using default tag: latest
> latest: Pulling from kklldog/agile_config
> Digest: sha256:c13a870d46f988674291a5e53c6c43efdc0edec727a0df42ecf8cdab22de8be0
> Status: Image is up to date for kklldog/agile_config:latest
> docker.io/kklldog/agile_config:latest
> `

是不是使用了国内镜像源没有来得及更新？

**Comment by wlclass** [comment]
确实是镜像源的问题，谢谢，
使用新版本后，上述问题解决。
